version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ronpai-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    depends_on:
      - db
    ports:
      - "9001:9000"  # ホストの9001ポートをコンテナの9000ポートにマッピング

  db:
    image: mysql:8.0
    container_name: ronpai-db
    environment:
      MYSQL_DATABASE: ronpai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ronpai
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"  # ホストの3307ポートをコンテナの3306ポートにマッピング
    volumes:
      - db-data:/var/lib/mysql

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ronpai-apache
    ports:
      - "8080:80"  # ホストの8080ポートをコンテナの80ポートにマッピング
    volumes:
      - ./src:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
      - app

volumes:
  db-data:
